version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: tasks_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata_tasks:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: tasks_backend_api
    ports:
      - "3002:3001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tasks_db
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: .
    container_name: tasks_frontend_react
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata_tasks: